<div>
    <meta httpEquiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Module ErgoSpec.Backend.Model.ErgoBackendModel</title>
    <meta
      name="description"
      content="Documentation of Coq module ErgoSpec.Backend.Model.ErgoBackendModel"
    />
    <link href="coq2html.css" rel="stylesheet" type="text/css" />
    <h1 className="title">Module ErgoSpec.Backend.Model.ErgoBackendModel</h1>
    <div className="coq">
      <br />
      <span className="kwd">
        Require
      </span> <span className="kwd">Import</span>{" "}
      <span className="id">
        <a href="https://querycert.github.io/html/Qcert.Common.CommonSystem.html">
          Qcert.Common.CommonSystem
        </a>
      </span>
      .<br />
      <br />
      <span className="kwd">
        Require
      </span> <span className="kwd">Import</span>{" "}
      <span className="id">
        <a href="ErgoSpec.Backend.Model.ErgoEnhancedModel.html">
          ErgoSpec.Backend.Model.ErgoEnhancedModel
        </a>
      </span>
      .<br />
      <span className="kwd">
        Require
      </span> <span className="kwd">Import</span>{" "}
      <span className="id">
        <a href="ErgoSpec.Backend.ForeignErgo.html">
          ErgoSpec.Backend.ForeignErgo
        </a>
      </span>
      .<br />
      <br />
      <span className="kwd">Module</span> <span className="kwd">Type</span>{" "}
      <span className="id">
        <a name="ErgoBackendModel">ErgoBackendModel</a>
      </span>
      .<br />
      &nbsp;&nbsp;<span className="kwd">Definition</span>{" "}
      <span className="id">
        <a name="ErgoBackendModel.ergo_foreign_data">ergo_foreign_data</a>
      </span>{" "}
      :{" "}
      <span className="id">
        <a href="https://querycert.github.io/html/Qcert.Common.DataModel.ForeignData.html#foreign_data">
          foreign_data
        </a>
      </span>{" "}
      :={" "}
      <span className="id">
        <a href="ErgoSpec.Backend.Model.ErgoEnhancedModel.html#enhanced_foreign_data">
          enhanced_foreign_data
        </a>
      </span>
      .<br />
      &nbsp;&nbsp;<span className="kwd">Axiom</span>{" "}
      <span className="id">
        <a name="ErgoBackendModel.ergo_data_to_json_string">
          ergo_data_to_json_string
        </a>
      </span>{" "}
      :{" "}
      <span className="id">
        <a href="http://coq.inria.fr/library/Coq.Strings.String.html#string">
          String.string
        </a>
      </span>{" "}
      -&gt;{" "}
      <span className="id">
        <a href="https://querycert.github.io/html/Qcert.Common.DataModel.Data.html#data">
          data
        </a>
      </span>{" "}
      -&gt;{" "}
      <span className="id">
        <a href="http://coq.inria.fr/library/Coq.Strings.String.html#string">
          String.string
        </a>
      </span>
      .<br />
      &nbsp;&nbsp;<span className="kwd">Definition</span>{" "}
      <span className="id">
        <a name="ErgoBackendModel.ergo_foreign_type">ergo_foreign_type</a>
      </span>{" "}
      :{" "}
      <span className="id">
        <a href="https://querycert.github.io/html/Qcert.Common.TypeSystem.ForeignType.html#foreign_type">
          foreign_type
        </a>
      </span>{" "}
      :={" "}
      <span className="id">
        <a href="ErgoSpec.Backend.Model.ErgoEnhancedModel.html#enhanced_foreign_type">
          enhanced_foreign_type
        </a>
      </span>
      .<br />
      <span className="kwd">End</span>{" "}
      <span className="id">
        <a href="ErgoSpec.Backend.Model.ErgoBackendModel.html#ErgoBackendModel">
          ErgoBackendModel
        </a>
      </span>
      .<br />
      <br />
    </div>
    <div className="footer">
      <hr />
      Generated by <a href="https://github.com/xavierleroy/coq2html/">coq2html</a>
    </div>
    <a href="https://github.com/xavierleroy/coq2html/"></a>
  </div>;
  