name: Build and Deploy

on:
  push:
    branches: 
      - main

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:

  build:

    runs-on: ubuntu-latest
    environment: production
    timeout-minutes: 30

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'

        # Ensure npm 11.5.1 or later for trusted publishing
      - run: npm install -g npm@latest

      - name: NPM Install
        if: github.ref == 'refs/heads/main'
        working-directory: ./website
        run: npm install

      - name: NPM Lint
        if: github.ref == 'refs/heads/main'
        working-directory: ./website
        run: npm run lint

      - name: NPM Build
        if: github.ref == 'refs/heads/main'
        working-directory: ./website
        run: npm run build

      - name: configure aws credentials
        if: github.ref == 'refs/heads/main'
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to S3
        if: github.ref == 'refs/heads/main'
        run: |
          aws s3 sync website/build s3://${{ secrets.AWS_S3_BUCKET }} \
            --acl public-read \
            --follow-symlinks \
            --delete
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Invalidate Cloudfront
        if: github.ref == 'refs/heads/main'
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
